version: '3'
services:
  samba:
    image: padiazg/samba4dc:ubuntu
    privileged: true
    environment:
      - SAMBA_DOMAIN=local
      - SAMBA_REALM=local.patodiaz.io
      - SAMBA_ADMIN_PASSWORD=secr3t*
      - LDAP_ALLOW_INSECURE=true
    volumes:
      - ~/tmp/smb-conf:/etc/samba
      - ~/tmp/krb-conf/krb5.conf:/etc/krb5.conf
      - samba4ad-smb-data:/var/lib/samba
      - samba4ad-krb-data:/var/lib/krb5kdc
    ports:
      # - "53:53"     # dns
      - "389:389"     # ldap
      # - "88:88"     # kdc
      # - "135:135"   # rpc
      # - "139:139"   # smbd
      # - "445:445"   # smbd
      # - "464:464"   # kdc
      - "3268:3268"   # ldap
      - "3269:3269"   # ldap 

volumes:
  samba4ad-smb-data:
  samba4ad-krb-data: